version: '3.8'

services:
  projection-service:
    build: .
    container_name: projection-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
